# Pipeline from https://www.eliostruyf.com/publishing-vscode-extensions-github-actions/

# This GitHub Actions workflow automatically publishes the VSCode extension to the Visual Studio Code Marketplace upon a new release being published.
# It checks out the code, sets up a Node.js environment, installs dependencies, installs the vsce tool.
# Then publishes the extension using a Personal Access Token (PAT) stored in the repository's secrets.

name: Release
on:
  release:
    types:
      - published # Triggered when a release is published. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Checks out the repository code.

      - uses: actions/setup-node@v2 # Sets up Node.js environment.
        with:
          node-version: '16' # Node 16 for vsce compatibility

      - name: Install dependencies
        run: npm install

      - name: Install vsce # Installs the vsce tool
        run: npx vsce --version || npm install -g vsce # Installs the vsce tool globally. https://code.visualstudio.com/api/working-with-extensions/publishing-extension

      - name: Publish Extension to VS Code Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }} # Use the PAT stored in GitHub Secrets
